# -*- coding: utf-8 -*-
"""Adease Time Series Forecasting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vK1CHUxOLVEcJEcSwv35K6CPXZnC6J3F

# **Problem statement:**
Ad ease is marketing company which helps client identify popular wikipedia pages of particular region so that they can show ads on those popular wikipedia pages. Showing ads on popular wikipedia pages increases the chances of user clicking on those ads also increases the chances of user purchasing  products. Forecasting the number of visits of wikipedia pages in future will help Adease identify popular wikipedia pages and they can show ads more effectively to generate maximum click through rates.

In this project we will use the data of number of visits of different wikipedia pages of different regions to build a model which will forecast the number of visits of those pages in coming days by using different timeseries forecasting methods. From the forecasting results, then we can easily identify the wikipedia pages which are more likely to be visited by maximum number of users & plan the advertising strategies more effectively.
"""

# importing necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

original_data = pd.read_csv('train_1.csv')
original_en_exog = pd.read_csv('Exog_Campaign_eng.csv')

# Create copy of data
df = original_data.copy()
en_exog = original_en_exog.copy()

"""# Data observation:"""

df.head(3)

len(df)

"""1. Dataset contains the information of number of visits of wikipedia pages for 551 days.
2. Total number of wikipeddia pages are 145063

"""

# Data type and information on null counts
df.info()

df.columns

df.isnull().sum()

"""1. Dataset has 145063 rows.
2. Data is from date 2015-07-01 to 2016-12-31.
3. All the columns contain nulls.

# Language code extraction:

Now we will extract the langauge code from wikipedia url link. All the links don't have langauge code inside them. We will not use the links in which there is no language code.

We are analysing the number of page visits in different languages therefore wikipedia links in which there is no langauge code is not useful to us therfore we will exclude them.

To do this first we will extract the language code then keep only those rows which have valid labguage code.
"""

# Extracting language code from each wikipedia link.
df['language_code'] = df.Page.str.split('.wikipedia.org_', expand=True)[0].apply(lambda x:x.split('_')[-1])
df['language_code']

# Now we will identify invalid language code.
lang_code = list(df.language_code.unique())
lang_code

#Spider and all-agents are not language codes of any language therefore we will not use these links.
df=df[~((df.language_code=='spider') | (df.language_code=='all-agents'))]
valid_lang_code = list(df.language_code.unique())
valid_lang_code

# Now we have dataset with only valid language codes.
# Check of how many rows we have in dataset after removing invalid wikipedia links.
print(f'Number of rows in data set are: {len(df)}')

"""After removing invalid language code links we have around 127000 wikipedia page data.

# Converting data to a suitable format:

We have data of wikipedia page visits for 551 days for different languages.
To convert data in the form of number of wikipedia page visits per day for each language we will aggregate data by summing the number of page visits on each day for different language.
"""

data=df.groupby('language_code').sum().reset_index().drop('Page',axis=1)
col = list(data.language_code)
data=data.T
data=data.iloc[1:].reset_index()
data.columns=['date','german','english','spanish','french','japanese','russian','chinese']
data.date=pd.to_datetime(data.date)
for i in data.columns[1::]:
  data[i]=data[i].astype('float')
data

"""Now we have data in proper format."""

# Check of datatype of each column and null value counts
data.info()

"""There are no null values in converted data."""

# Statistical summary of data
data.describe()

# Checking duplicate records in converted data.
data.duplicated().any()

"""There are no duplicate records in dataset.

# **Exploratory data analysis:**
"""

# Plotting histogram and boxplot.
for col in data.columns[1::]:
  plt.figure(figsize=(20,6))
  plt.subplot(1,3,1)
  sns.histplot(data[col])
  plt.subplot(1,3,2)
  sns.kdeplot(data[col])
  plt.subplot(1,3,3)
  sns.boxplot(data[col])
  plt.show()

"""Insights:
From the above plots we can see that number of visits to wikipedia pages for each language follows the normal distribution with some outliers.
Same pattern we can see in distribution plots across all the lanaguages.
"""

for i in data.columns[1::]:
  plt.figure(figsize=(20,5))
  sns.lineplot(data=data,x=data.date,y=data[i])
  plt.show()

"""Insights:
1. Timeseries plot of german wikipedia pages: There is short term and long term seasonality in timeseries plot of german wikipedia pages. Plot also shows gradual upward trend from biginning to end of plot.
2. Timeseries plot of english wikipedia pages: In this timeseries plot also we can see short term seasonality and upwards trend. From this plot we can see that there is sudden spike in number of page visits fro july 2016 to september 2016.
3. Timeseries plot of spanish wikipedia pages: In this plot we can see the short term and long term seasonality in number of visits to wikipedia pages. There is upward trend also in this plot.
4. Timeseries plot of french wikipedia pages: We can see short term seasonality and upward trend in this timeseries plot. There is sudden increase in number of visits to wikipedia pages in the month of april 2016 and may 2016.
5. Timeseries plot of japanese wikipedia pages: There is short term seasonality in this plot and upward trend. From the plot we can see that there are sudden spikes also in the plot, these spikes may be because of some external variable.
6. Time series plot of russian wikipedia pages: There is short term seasonality in this plot and upward trend. From the plot we can sudden increase in number of page visits in the month of september 2016 and october 2016.
7. Timeseries plot of chinese wikipedia pages: In this timeseries plot we can see short term and upward trend.


"""

# We will have to separate data for each langauage and then build model on them.
data.head(3)

german = data[['date','german']].set_index('date')
english = data[['date','english']].set_index('date')
spanish = data[['date','spanish']].set_index('date')
french = data [['date','french']].set_index('date')
japanese = data[['date','japanese']].set_index('date')
russian = data[['date','russian']].set_index('date')
chinese = data[['date','chinese']].set_index('date')

"""For building arima and sarimax models data should not be stationary, we will now check the stationarity of data by using dicky fuller test."""

import statsmodels.api as sm

# Stationarity check on each language data.
def stationary_test(dataset):
  p_value = sm.tsa.stattools.adfuller(dataset)[1]
  if p_value<0.05:
    print(' stationary')
  else:
    print(' not stationary')

lang = [['german',german],['english',english],['spanish',spanish],['french',french],['japanese',japanese],['russian',russian],['chinese',chinese]]
for i in lang:
  p_value = sm.tsa.stattools.adfuller(i[1])[1]
  if p_value<0.05:
    print(f'{i[0]} series is stationary')
  else:
    print(f'{i[0]} series is not stationary')

"""1. Non stationary series are german, english, french, japanese and chinese.
2. Stationary series are spanish and russian.

To identify the seasonality of data we will use ACF and PACF plots.Identifying seasonality is important for detrending and deseasning the series.

We will individually plot the ACF AND PACF plots and then identify seasonality from plots for each language.

1. German language
"""

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

plt.rcParams['figure.figsize'] = (20,6)

plot_acf(german);

"""From above plot we can see that there is weekly seasonality in this series."""

plot_pacf(german);

"""From this plot also we can see that there is weekly seasonality in this series.

We will split the data in train and test set to builr the forecating models. From the baove plot we can see that there is weekly seasonality therefore last four weeks data we will use for testing and rest for training.
"""

# train test split
index = german.index[-28]
german_train = german[german.index<index]
german_test = german[german.index>=index]

"""Detrending train data."""

# detrending the data
german_train_st = german_train.german.diff(1).dropna()

# check of stationarity on detrended data
stationary_test(german_train_st)

"""Now the series is stationary."""

# acf and pacf plot on detrended series
plot_acf(german_train_st);
plot_pacf(german_train_st);

"""From these plots also we can see weekly seasonality

2. English language
"""

plot_acf(english);

plot_pacf(english);

"""From these plots we can see that there is weekly seasonality in english language series also.

Now we will split the data in training and testing set and make the series stationary by detrending.
"""

# train test split
index = english.index[-28]
english_train = english[english.index<index]
english_test = english[english.index>=index]

# detrending the data
english_train_st = english_train.english.diff(1).dropna()

# check of stationarity on detrended data
stationary_test(english_train_st)

"""Now english series is also stationary."""

# acf and pacf plot on detrended series
plot_acf(english_train_st);
plot_pacf(english_train_st);

"""From these plots also we can see weekly seasonality

3. Spanish language

ACF and PACF plots to identify seasonality
"""

# acf and pacf plots
plot_acf(spanish);
plot_pacf(spanish);

"""From these plots also we can see that there is weekly seasonality in spanish series.

Now will split the data and make it stationary by detrending.
"""

# train test split
index = spanish.index[-28]
spanish_train = spanish[spanish.index<index]
spanish_test = spanish[spanish.index>=index]

# detrending the data
spanish_train_st = spanish_train.spanish.diff(1).dropna()

# check of stationarity on detrended data
stationary_test(spanish_train_st)

"""Now this series is also stationary"""

# acf and pacf plot on detrended series
plot_acf(spanish_train_st);
plot_pacf(spanish_train_st);

"""From these plots also we can see weekly seasonality

4. French language
"""

# acf and pacf plots to identify seasonality
plot_acf(french);
plot_pacf(french);

"""From these plots also we can see that there is weekly seasonality in this series.

Now we will split the data and make the series stationary.
"""

# train test split
index = french.index[-28]
french_train = french[french.index<index]
french_test = french[french.index>=index]

# detrending the data
french_train_st = french_train.french.diff(1).dropna()

# check of stationarity on detrended data
stationary_test(french_train_st)

"""Now this series is stationary"""

# acf and pacf plot on detrended series
plot_acf(french_train_st);
plot_pacf(french_train_st);

"""From these plots also we can see weekly seasonality

5. Japanese language
"""

# acf and pacf plots to identify seasonality
plot_acf(japanese);
plot_pacf(japanese);

"""In this series also there is weekly seasonality.
Now we will split the series and make it staionary.
"""

# train test split
index = japanese.index[-28]
japanese_train = japanese[japanese.index<index]
japanese_test = japanese[japanese.index>=index]

# detrending the data
japanese_train_st = japanese_train.japanese.diff(1).dropna()

# check of stationarity on detrended data
stationary_test(japanese_train_st)

"""Now this series is stationary."""

# acf and pacf plot on detrended series
plot_acf(japanese_train_st);
plot_pacf(japanese_train_st);

"""From autocorrelation plot of detrended data we can see weekly seasonality, there is no pattern in partial autocorrelation plot of detrended data.

6. Russian language
"""

# acf and pacf plots to identify seasonality
plot_acf(russian);
plot_pacf(russian);

"""From these plot we can't see any seasonality.
Now we will split the data and make it stationary.
"""

# train test split
index = russian.index[-28]
russian_train = russian[russian.index<index]
russian_test = russian[russian.index>=index]

# detrending the data
russian_train_st = russian_train.russian.diff(1).dropna()

# check of stationarity on detrended data
stationary_test(russian_train_st)

"""Now this series is also stationary."""

# acf and pacf plot on detrended series
plot_acf(russian_train_st);
plot_pacf(russian_train_st);

"""There is no pattern in acf and pacf plots of detrended data.

7. Chinese language
"""

# acf and pacf plots to identify seasonality
plot_acf(chinese);
plot_pacf(chinese);

"""In this series there is weekly seasonality"""

# train test split
index = chinese.index[-28]
chinese_train = chinese[chinese.index<index]
chinese_test = chinese[chinese.index>=index]

# detrending the data
chinese_train_st = chinese_train.chinese.diff(1).dropna()

# check of stationarity on detrended data
stationary_test(chinese_train_st)

"""Now this series is also stationary."""

# acf and pacf plot on detrended series
plot_acf(chinese_train_st);
plot_pacf(chinese_train_st);

"""From these plots we can see weekly seasonality.

Now we will build ARIMA model on all these series.

1. ARIMA model on german series.
"""

from statsmodels.tsa.statespace.sarimax import SARIMAX

"""From the acf and pacf plots we can see that values gradually decreases till third, fourth and fifth lag so we will can take pand Q values between 3 to 5. Plot looks linear so will use d value as 1."""

from sklearn.metrics import mean_absolute_percentage_error as mape

def performance(x,y):
  print('MAPE:',mape(x,y))

model_arima_ger = SARIMAX(german_train.german, order=(3,1,3))
model_arima_ger = model_arima_ger.fit(disp=False)
german_test['pred'] = model_arima_ger.forecast(steps=28)
german_test.plot(style='-o')
performance(german_test.german,german_test.pred)

model1_arima_ger = SARIMAX(german_train.german, order=(4,1,4))
model1_arima_ger = model1_arima_ger.fit(disp=False)
german_test['pred'] = model1_arima_ger.forecast(steps=28)
german_test.plot(style='-o')
performance(german_test.german,german_test.pred)

model2_arima_ger = SARIMAX(german_train.german, order=(5,1,5))
model2_arima_ger = model2_arima_ger.fit(disp=False)
german_test['pred'] = model1_arima_ger.forecast(steps=28)
german_test.plot(style='-o')
performance(german_test.german,german_test.pred)

"""Mean absolute percentage error value is less for p and q values of 3 and for 4 and 5 therefore we will use first ARIMA model.

From acf and pacf plots we can see same pattern for all the series except for russian series so we will use p,d and q values as 3,1,3 for all models and will check the performance for other values of p and q.

2. ARIMA model for english langauage series.
"""

model_arima_eng = SARIMAX(english_train.english, order=(3,1,3))
model_arima_eng = model_arima_eng.fit(disp=False)
english_test['pred'] = model_arima_eng.forecast(steps=28)
english_test.plot(style='-o')
performance(english_test.english,english_test.pred)

model1_arima_eng = SARIMAX(english_train.english, order=(4,1,4))
model1_arima_eng = model1_arima_eng.fit(disp=False)
english_test['pred'] = model1_arima_eng.forecast(steps=28)
english_test.plot(style='-o')
performance(english_test.english,english_test.pred)

model2_arima_eng = SARIMAX(english_train.english, order=(5,1,5))
model2_arima_eng = model2_arima_eng.fit(disp=False)
english_test['pred'] = model2_arima_eng.forecast(steps=28)
english_test.plot(style='-o')
performance(english_test.english,english_test.pred)

"""First model is wrking well for p and q values of 3 so we will use first model for this series.

From above two models we can see that pperformance is good for p and q values of 3 than for 4 and 5 so for further models we will use p and q value as 3.

3. ARIMA model for spanish series.
"""

model_arima_spn = SARIMAX(spanish_train.spanish, order=(3,1,3))
model_arima_spn = model_arima_spn.fit(disp=False)
spanish_test['pred'] = model_arima_spn.forecast(steps=28)
spanish_test.plot(style='-o')
performance(spanish_test.spanish,spanish_test.pred)

"""ARIMA model of this series is giving mape value of 7.5 %.

4. ARIMA model for french series
"""

model_arima_fr = SARIMAX(french_train.french, order=(3,1,3))
model_arima_fr = model_arima_fr.fit(disp=False)
french_test['pred'] = model_arima_fr.forecast(steps=28)
french_test.plot(style='-o')
performance(french_test.french,french_test.pred)

"""5. ARIMA model for japanese series"""

model_arima_jpn = SARIMAX(japanese_train.japanese, order=(3,1,3))
model_arima_jpn = model_arima_jpn.fit(disp=False)
japanese_test['pred'] = model_arima_jpn.forecast(steps=28)
japanese_test.plot(style='-o')
performance(japanese_test.japanese,japanese_test.pred)

"""6. ARIMA model for russian language series.

From acf and pacf plots we can't see any pattern so will try some values for p and q and check which model is performing well.
"""

model_arima_rus = SARIMAX(russian_train.russian, order=(3,1,3))
model_arima_rus = model_arima_rus.fit(disp=False)
russian_test['pred'] = model_arima_rus.forecast(steps=28)
russian_test.plot(style='-o')
performance(russian_test.russian,russian_test.pred)

model1_arima_rus = SARIMAX(russian_train.russian, order=(4,1,4))
model1_arima_rus = model1_arima_rus.fit(disp=False)
russian_test['pred'] = model1_arima_rus.forecast(steps=28)
russian_test.plot(style='-o')
performance(russian_test.russian,russian_test.pred)

model2_arima_rus = SARIMAX(russian_train.russian, order=(5,1,5))
model2_arima_rus = model2_arima_rus.fit(disp=False)
russian_test['pred'] = model2_arima_rus.forecast(steps=28)
russian_test.plot(style='-o')
performance(russian_test.russian,russian_test.pred)

"""First model is performing well so we will use first model for forecasting for russian series.

7. ARIMA model for chinese series.
"""

model_arima_ch = SARIMAX(chinese_train.chinese, order=(3,1,3))
model_arima_ch = model_arima_ch.fit(disp=False)
chinese_test['pred'] = model_arima_ch.forecast(steps=28)
chinese_test.plot(style='-o')
performance(chinese_test.chinese,chinese_test.pred)

"""B. Now we will build SARIMA and SARIMAX models for all the language series.

1. SARIMA model for german language.

All the series have seasonality of 7 days so we will use weekly seaonality for models of all the language series.
"""

model_sarima_ger = SARIMAX(german_train.german, order=(3,1,3), seasonal_order=(1,1,1,7))
model_sarima_ger = model_sarima_ger.fit(disp=False)
german_test['pred'] = model_sarima_ger.forecast(steps=28)
german_test.plot(style='-o')
performance(german_test.german,german_test.pred)

"""2. SARIMA and SARIMAX model for english language."""

# SARIMA model
model_sarima_eng = SARIMAX(english_train.english, order=(3,1,3), seasonal_order=(1,1,1,7))
model_sarima_eng = model_sarima_eng.fit(disp=False)
english_test['pred'] = model_sarima_eng.forecast(steps=28)
english_test.plot(style='-o')
performance(english_test.english,english_test.pred)

"""SARIMAX model"""

english_train['exog']=original_en_exog[original_en_exog.index<522].values

# SARIMAX model
model_sarimax_eng = SARIMAX(english_train.english, exog=english_train.exog,order=(3,1,3), seasonal_order=(1,1,1,7))
model_sarimax_eng = model_sarimax_eng.fit(disp=False)
english_test['pred'] = model_sarimax_eng.predict(start=521, end=550,exog=original_en_exog[521:][['Exog']])
english_test.plot(style='-o')
performance(english_test.english,english_test.pred)

"""This model with exogneous valiable is giving least error so we will use this model for forecasting.

3. SARIMA model for spanish language.
"""

# SARIMA model
model_sarima_spn = SARIMAX(spanish_train.spanish, order=(3,1,3), seasonal_order=(1,1,1,7))
model_sarima_spn = model_sarima_spn.fit(disp=False)
spanish_test['pred'] = model_sarima_spn.forecast(steps=28)
spanish_test.plot(style='-o')
performance(spanish_test.spanish,spanish_test.pred)

"""4. SARIMA model from french language."""

# SARIMA model
model_sarima_fr = SARIMAX(french_train.french, order=(3,1,3), seasonal_order=(1,1,1,7))
model_sarima_fr = model_sarima_fr.fit(disp=False)
french_test['pred'] = model_sarima_fr.forecast(steps=28)
french_test.plot(style='-o')
performance(french_test.french,french_test.pred)

"""5. SARIMA model for japanese language."""

# SARIMA model
model_sarima_jpn = SARIMAX(japanese_train.japanese, order=(3,1,3), seasonal_order=(1,1,1,7))
model_sarima_jpn = model_sarima_jpn.fit(disp=False)
japanese_test['pred'] = model_sarima_jpn.forecast(steps=28)
japanese_test.plot(style='-o')
performance(japanese_test.japanese,japanese_test.pred)

"""6. SARIMA model for russian language."""

# SARIMA model
model_sarima_rus = SARIMAX(russian_train.russian, order=(3,1,3), seasonal_order=(1,1,1,7))
model_sarima_rus = model_sarima_rus.fit(disp=False)
russian_test['pred'] = model_sarima_rus.forecast(steps=28)
russian_test.plot(style='-o')
performance(russian_test.russian,russian_test.pred)

# SARIMA model
model_sarima_rus = SARIMAX(russian_train.russian, order=(3,1,3), seasonal_order=(2,2,2,7))
model_sarima_rus = model_sarima_rus.fit(disp=False)
russian_test['pred'] = model_sarima_rus.forecast(steps=28)
russian_test.plot(style='-o')
performance(russian_test.russian,russian_test.pred)

"""Second model is giving better results so we will use second model for forecasting.

7. SARIMA model for chinese wikipedia pages.
"""

# SARIMA model
model_sarima_ch = SARIMAX(chinese_train.chinese, order=(3,1,3), seasonal_order=(1,1,1,7))
model_sarima_ch = model_sarima_ch.fit(disp=False)
chinese_test['pred'] = model_sarima_ch.forecast(steps=28)
chinese_test.plot(style='-o')
performance(chinese_test.chinese,chinese_test.pred)

model_sarima_ch = SARIMAX(chinese_train.chinese, order=(3,1,3), seasonal_order=(2,2,2,7))
model_sarima_ch = model_sarima_ch.fit(disp=False)
chinese_test['pred'] = model_sarima_ch.forecast(steps=28)
chinese_test.plot(style='-o')
performance(chinese_test.chinese,chinese_test.pred)

"""First model is performing well so we will use first model for forecasting.

# **FB prophet models**

Now we will build fb prophet model on all language series.
"""

!pip install prophet
!pip install cmdstanpy
import cmdstanpy
cmdstanpy.install_cmdstan()

from prophet import Prophet

"""1. German language series."""

german_train_p = pd.DataFrame()
german_train_p['ds']=german_train.index
german_train_p['y']=german_train['german'].values
german_train_p

# prophet model for german series
model_prophet_ger = Prophet(weekly_seasonality=True)
model_prophet_ger.fit(german_train_p)

future = model_prophet_ger.make_future_dataframe(periods=28,freq='D')
forecast=model_prophet_ger.predict(future)
german_test['pred']= forecast['yhat'][522:].values

german_test.plot(style='-o')
performance(german_test.german,german_test.pred)

# prophet model for german series
model_prophet_ger = Prophet(weekly_seasonality=True,
                            yearly_seasonality=True)
model_prophet_ger.fit(german_train_p)

future = model_prophet_ger.make_future_dataframe(periods=28,freq='D')
forecast=model_prophet_ger.predict(future)
german_test['pred']= forecast['yhat'][522:].values

german_test.plot(style='-o')
performance(german_test.german,german_test.pred)

fig = model_prophet_ger.plot(forecast)

"""Secind model is performing well with mape value of 6% so we will use second model.

2. Prophet model for english series.
"""

# Converting data to a suitable format.
english_train_p = pd.DataFrame()
english_train_p['ds']=english_train.index
english_train_p['y']=english_train['english'].values
english_train_p['holiday']=en_exog['Exog'][:522].values
english_train_p

# prophet model
model_prophet_en = Prophet()
model_prophet_en.add_regressor('holiday')
model_prophet_en.fit(english_train_p)

future = model_prophet_en.make_future_dataframe(periods=28,freq='D')
future['holiday']=en_exog['Exog'].values
forecast=model_prophet_en.predict(future)
english_test['pred']= forecast['yhat'][522:].values

english_test.plot(style='-o')
performance(english_test.english,english_test.pred)

# prophet model for german series
model_prophet_en = Prophet(weekly_seasonality=True)
model_prophet_en.add_regressor('holiday')
model_prophet_en.fit(english_train_p)

future = model_prophet_en.make_future_dataframe(periods=28,freq='D')
future['holiday']=en_exog['Exog'].values
forecast=model_prophet_en.predict(future)
english_test['pred']= forecast['yhat'][522:].values

english_test.plot(style='-o')
performance(english_test.english,english_test.pred)

# prophet model for german series
model_prophet_en = Prophet(weekly_seasonality=True,
                           yearly_seasonality=True)
model_prophet_en.add_regressor('holiday')
model_prophet_en.fit(english_train_p)

future = model_prophet_en.make_future_dataframe(periods=28,freq='D')
future['holiday']=en_exog['Exog'].values
forecast=model_prophet_en.predict(future)
english_test['pred']= forecast['yhat'][522:].values

english_test.plot(style='-o')
performance(english_test.english,english_test.pred)

"""Third model is performing well with mape value of 4%, so we will use third model for forecasting which has weekly and yearly seasonality."""

# Visualisong forecast.
fig = model_prophet_en.plot(forecast)

"""3. Prophet model for spanish language."""

# Converting data to a suitable format.
spanish_train_p = pd.DataFrame()
spanish_train_p['ds']=spanish_train.index
spanish_train_p['y']=spanish_train['spanish'].values

# prophet model
model_prophet_sp = Prophet()
model_prophet_sp.fit(spanish_train_p)

future = model_prophet_sp.make_future_dataframe(periods=28,freq='D')
forecast=model_prophet_sp.predict(future)
spanish_test['pred']= forecast['yhat'][522:].values

spanish_test.plot(style='-o')
performance(spanish_test.spanish,spanish_test.pred)

# prophet model
model_prophet_sp = Prophet(weekly_seasonality=True,
                           yearly_seasonality=True)
model_prophet_sp.fit(spanish_train_p)

future = model_prophet_sp.make_future_dataframe(periods=28,freq='D')
forecast=model_prophet_sp.predict(future)
spanish_test['pred']= forecast['yhat'][522:].values

spanish_test.plot(style='-o')
performance(spanish_test.spanish,spanish_test.pred)

"""second model is performing well with mape value of 11% so we will use second model."""

# Visualisong forecast.
fig = model_prophet_sp.plot(forecast)

"""4. Prophet model for french language."""

# Converting data to a suitable format.
french_train_p = pd.DataFrame()
french_train_p['ds']=french_train.index
french_train_p['y']=french_train['french'].values

# prophet model
model_prophet_fr = Prophet()
model_prophet_fr.fit(french_train_p)

future = model_prophet_fr.make_future_dataframe(periods=28,freq='D')
forecast=model_prophet_fr.predict(future)
french_test['pred']= forecast['yhat'][522:].values

french_test.plot(style='-o')
performance(french_test.french,french_test.pred)

# prophet model
model_prophet_fr = Prophet(weekly_seasonality=True)
model_prophet_fr.fit(french_train_p)

future = model_prophet_fr.make_future_dataframe(periods=28,freq='D')
forecast=model_prophet_fr.predict(future)
french_test['pred']= forecast['yhat'][522:].values

french_test.plot(style='-o')
performance(french_test.french,french_test.pred)

"""Models with and without seasonality componant are performing in a similar way, but we will use seond one which has seasonality componant."""

# Visualisong forecast.
fig = model_prophet_fr.plot(forecast)

"""5. Prophet model for japanese language."""

# Converting data to a suitable format.
japanese_train_p = pd.DataFrame()
japanese_train_p['ds']=japanese_train.index
japanese_train_p['y']=japanese_train['japanese'].values

# prophet model
model_prophet_jpn = Prophet()
model_prophet_jpn.fit(japanese_train_p)

future = model_prophet_jpn.make_future_dataframe(periods=28,freq='D')
forecast=model_prophet_jpn.predict(future)
japanese_test['pred']= forecast['yhat'][522:].values

japanese_test.plot(style='-o')
performance(japanese_test.japanese,japanese_test.pred)

# prophet model with seasonality
model_prophet_jpn = Prophet(weekly_seasonality=True,
                            yearly_seasonality=True)
model_prophet_jpn.fit(japanese_train_p)

future = model_prophet_jpn.make_future_dataframe(periods=28,freq='D')
forecast=model_prophet_jpn.predict(future)
japanese_test['pred']= forecast['yhat'][522:].values

japanese_test.plot(style='-o')
performance(japanese_test.japanese,japanese_test.pred)

"""Second model with seasonality componant is performing well so we will use second model for forecasting."""

# Visualisong forecast.
fig = model_prophet_jpn.plot(forecast)

"""6. Prophet model for russian language."""

# Converting data to a suitable format.
russian_train_p = pd.DataFrame()
russian_train_p['ds']=russian_train.index
russian_train_p['y']=russian_train['russian'].values

# prophet model
model_prophet_rs = Prophet(weekly_seasonality=True,
                           yearly_seasonality=True)
model_prophet_rs.fit(russian_train_p)

future = model_prophet_rs.make_future_dataframe(periods=28,freq='D')
forecast=model_prophet_rs.predict(future)
russian_test['pred']= forecast['yhat'][522:].values

russian_test.plot(style='-o')
performance(russian_test.russian,russian_test.pred)

# prophet model without seasonality componant.
model_prophet_rs = Prophet()
model_prophet_rs.fit(russian_train_p)

future = model_prophet_rs.make_future_dataframe(periods=28,freq='D')
forecast=model_prophet_rs.predict(future)
russian_test['pred']= forecast['yhat'][522:].values

russian_test.plot(style='-o')
performance(russian_test.russian,russian_test.pred)

"""Second model is performing well so we will use second model for forecasting."""

# Visualisong forecast.
fig = model_prophet_rs.plot(forecast)

"""7. Prophet model for chinese language."""

# Converting data to a suitable format.
chinese_train_p = pd.DataFrame()
chinese_train_p['ds']=chinese_train.index
chinese_train_p['y']=chinese_train['chinese'].values

# prophet model
model_prophet_ch = Prophet()
model_prophet_ch.fit(chinese_train_p)

future = model_prophet_ch.make_future_dataframe(periods=28,freq='D')
forecast=model_prophet_ch.predict(future)
chinese_test['pred']= forecast['yhat'][522:].values

chinese_test.plot(style='-o')
performance(chinese_test.chinese,chinese_test.pred)

# prophet model with seasonality componants
model_prophet_ch = Prophet(weekly_seasonality=True)
model_prophet_ch.fit(chinese_train_p)

future = model_prophet_ch.make_future_dataframe(periods=28,freq='D')
forecast=model_prophet_ch.predict(future)
chinese_test['pred']= forecast['yhat'][522:].values

chinese_test.plot(style='-o')
performance(chinese_test.chinese,chinese_test.pred)

"""Both models are performing well but we will use second model which has seasonality componant."""

# Visualisong forecast.
fig = model_prophet_ch.plot(forecast)

"""For all the language series now we have ARIMA, SARIMAX and prohet model, models which are giving less mape value we will use for forecasting.

# **Results interpretaion:**

1. In all the series except for russian series we saw that there is weekly seasonality in number of visits to wikipedia pages.
2. Days with hign number of visits are weekends (saturday & sunday), therefore ad ease can plan add recommondation strategy based on weekly seasonality.
3. German and english series has yearly seasonality also along with weekly seasonality, this may be because of christmas period at the end of the year.
4. performance of the model improved upon adding exogenous variable for english series, therefore holiday information for other langausge series can improve prediction accuracy.
5. During holiday's number of wikipedia page visits are more so adease can plan add recomondation strategy accordingly.
"""

english_train.groupby('exog').english.mean().plot(kind='pie')

"""From the above graph we can see that mean number of page visits on holidays are more as compared to other days and this information will be very useful for add reccomondation planning."""

data[['german',	'english',	'spanish',	'french',	'japanese',	'russian',	'chinese']].mean().plot(kind='bar')

"""6. Number of visits to english wikipedia pages is more as compared to other languages, english langauge is spoken in many countries and this might be the reason for more number of visits to english pages and this information is very useful for addease for add reccomondation planning.

Questionnaire:

1. Forecasted values of number of wikipedia pages for each language will be helpful for addease to identify the popular wikipedia pages and languages to plan add reccomondation strategy effectively. Forecasted values helps in many ways like planning in company schedules/activities, future workforce requirement, resource planning, required technica expertise etc.
2. In all the series except for russian series there is weekly sesonality, number of wikipedia page visits on holidays is more as compared to other day's, german english and japanese language series has yearly seasonality, number of visits to english pages is highest as compared to other languages.
3. Decomposition of series decomposes data into trend, seasonality and residual and helps identify seasonality in data.
4. By differencing the series by one day series was stationary.
5. ARIMA model based on auto regression and moving average, SARIMA model is based on auto regression moving average and seasonality componant, SARIMAX  model is based on auto regression, moving average,seasonality and external variables aslo like holiday, new product launch, economic slowdown etc.
6. Number of wikipedia page visits of english langauge are more than any other language page visits.
7. For hyperparameter tunning we can use grid search CV, randomized search CV and optuna.
"""